services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xys131313
      MYSQL_DATABASE: kog_production
      MYSQL_USER: root
      MYSQL_PASSWORD: xys131313
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/mysql_init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
