name: Build and Push Docker Image

# 当你推送到 main 分支，或者创建一个 v*.*.* 格式的 tag 时，此工作流会自动运行
on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    # 使用一台标准的、amd64架构的 Ubuntu 服务器
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出你的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 QEMU 以支持多平台构建 (好习惯)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置 Docker Buildx，这是现代化的构建工具
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. 构建并推送镜像
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platform: linux/amd64
          push: true
          # 自动使用你的分支名和 tag 作为镜像标签
          # 例如，推送到 main 会打上 latest 标签，推送到 v1.2.3 会打上 v1.2.3 标签
          tags: |
            victorxys/kog:latest
            victorxys/kog:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
